In [14]:
import numpy as np
from collections import namedtuple
import random

In [15]:
class Agent:
    def __init__(self, i=0,j=0):
        self.i=i
        self.j=j
    @property
    def loc(self):
        return(self.i,self.j)
    
    def vmove(self,direction):
        direction=1 if direction>0 else -1
        return Agent(self.i + direction, self.j)
    
    def hmove(self,direction):
        direction=1 if direction>0 else -1
        return Agent(self.i , direction+ self.j) 
    def __repr__(self):
        return str(self.loc)

In [16]:
# general maze class defination
class Maze:
   
    # init method or constructor
    
    # defining a general 4*4 matrix intialised as 0 matrix
    def __init__(self, rows=4,columns=4):
        self.env =np.zeros((4, 4))
        
        # mousy is object of Agent class
        self.mousy=Agent(0,0) 
        
    def in_bounds(self,i,j):
        nr,nc= self.env.shape
        return i>=0 and i<nr and j>=0 and j<nc
    
    def agent_in_bounds(self,a):
        return self.in_bounds(a.i,a.j)
    
    def agent_dient(self,a):
        return not self.env[a.i,a.j]== -1
    
    def is_valid_new_agent(self,a):
        return self.agent_in_bounds(a) and self.agent_dient(a)
        
       
    def compute_possible_moves(self):
        a=self.mousy
        moves=[
            a.vmove(1),
            a.vmove(-1),
            a.hmove(1),
            a.hmove(-1),
        ]        
        return [m for m in moves if self.is_valid_new_agent(m) ]
    
    def do_a_move(self,a):
        assert self.is_valid_new_agent(a),"Mousy can't go there"
        self.mousy=a
        return 10 if self.has_won() else -0.1
        
    def has_won(self):
        a=self.mousy
        return self.env[a.i,a.j]==1
        
    def visualise(self):
        assert self.agent_in_bounds(self.mousy), "mousy is out of bounds"
        ec=self.env.copy()
        mo=self.mousy
        ec[mo.i,mo.j]=6
        print(ec)
        

In [17]:
# A test maze we are trying to solve
def make_test_maze():
    m=Maze()
    e=m.env
    e[3,3]= 1
    e[0,1:3]=-1
    e[1,2:4]=-1
    e[3,0:2]=-1
    return m

In [24]:
def main():
    M = make_test_maze()
    M.visualise
    final_score=0
    while not M.has_won():
        moves=M.compute_possible_moves()
        random.shuffle(moves)
        M.mousy= moves[0]
        final_score+=M.do_a_move(moves[0])
        M.visualise()
    print("done")
    print("final_score=",final_score)
    

In [31]:
if __name__=="__main__":
    main()


[[ 0. -1. -1.  0.]
 [ 6.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  0. -1. -1.]
 [ 6.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 6.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 6. -1. -1.  0.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 6.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  6. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 6.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  6. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  0. -1. -1.]
 [ 0.  6.  0.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  6.  0.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  0.  6.]
 [-1. -1.  0.  1.]]
[[ 0. -1. -1.  0.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [-1. -1.  0.  6.]]
done
final_score= 8.9


In [2]:
name = "practice" 
print((name + " ") * 101)


practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice practice 
